# These are supported funding model platforms

github: manavspg2
patreon: manavspg2
open_collective: manavspg2
ko_fi: manavspg2
tidelift: manavspg2/AplacQuantop-em
community_bridge: AlpacQuantop-em
liberapay: manavspg2
issuehunt: manavspg2
otechie: manavspg2
custom: https://github.com/manavspg2/AlpacQuantop-em
